site_name: Misc Docs
site_url: https://docs.meteyou.wtf/
site_author: Stefan Dej (meteyou)

repo_name: meteyou/docs
repo_url: https://github.com/meteyou/docs

# add copyright to the footer
copyright: |
  &copy; 2024 <a href="https://github.com/meteyou"  target="_blank" rel="noopener">Stefan Dej (meteyou)</a>

# add some social media buttons to the footer
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/meteyou
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@meteyou
    - icon: fontawesome/brands/twitter
      link: https://x.com/meteyou

theme:
  name: material
  locale: en
  icon:
    logo: material/printer-3d
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# add some plugins
plugins:
  - redirects:
      redirect_maps:
        'btt-ebb/index.md' : '3d-printing/klipper/canbus/btt/ebb/index.md'
        'btt-ebb/canboot.md' : '3d-printing/klipper/canbus/btt/ebb/canboot.md'
        'btt-ebb/klipper.md' : '3d-printing/klipper/canbus/btt/ebb/klipper.md'
        'btt-u2c-v1.x/index.md' : '3d-printing/klipper/canbus/btt/u2c-v1.x/index.md'
        'btt-u2c-v1.x/candlelight.md' : '3d-printing/klipper/canbus/btt/u2c-v1.x/candlelight.md'
        'btt-u2c-v1.x/canboot.md' : '3d-printing/klipper/canbus/btt/u2c-v1.x/canboot.md'
        'btt-u2c-v1.x/klipper-usb-to-can.md' : '3d-printing/klipper/canbus/btt/u2c-v1.x/klipper-usb-to-can.md'
        'btt-u2c-v2.x/index.md' : '3d-printing/klipper/canbus/btt/u2c-v2.x/index.md'
        'btt-u2c-v2.x/candlelight.md' : '3d-printing/klipper/canbus/btt/u2c-v2.x/candlelight.md'
        'btt-u2c-v2.x/canboot.md' : '3d-printing/klipper/canbus/btt/u2c-v2.x/canboot.md'
        'btt-u2c-v2.x/klipper-usb-to-can.md' : '3d-printing/klipper/canbus/btt/u2c-v2.x/klipper-usb-to-can.md'
  - search

# add some markdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# full navigation structure
nav:
  - Home: index.md

  - CANBUS Guides:
    - BigTreeTech:
      - EBB series <i>(STM32)</i>:
        - Overview: 3d-printing/klipper/canbus/btt/ebb/index.md
        - CanBoot <i>(optional)</i>: 3d-printing/klipper/canbus/btt/ebb/canboot.md
        - Klipper: 3d-printing/klipper/canbus/btt/ebb/klipper.md
      - U2C Module (for BTT Pi v1.2): 3d-printing/klipper/canbus/btt/u2c-module/index.md
      - U2C v1.x:
        - Overview: 3d-printing/klipper/canbus/btt/u2c-v1.x/index.md
        - Candlelight: 3d-printing/klipper/canbus/btt/u2c-v1.x/candlelight.md
        - CanBoot <i>(optional)</i>: 3d-printing/klipper/canbus/btt/u2c-v1.x/canboot.md
        - Klipper USB-to-CAN: 3d-printing/klipper/canbus/btt/u2c-v1.x/klipper-usb-to-can.md
      - U2C v2.x:
        - Overview: 3d-printing/klipper/canbus/btt/u2c-v2.x/index.md
        - Candlelight: 3d-printing/klipper/canbus/btt/u2c-v2.x/candlelight.md
        - CanBoot <i>(optional)</i>: 3d-printing/klipper/canbus/btt/u2c-v2.x/canboot.md
        - Klipper USB-to-CAN: 3d-printing/klipper/canbus/btt/u2c-v2.x/klipper-usb-to-can.md
    - Mellow:
      - Fly SHT v1:
        - Overview: 3d-printing/klipper/canbus/mellow/fly-sht-v1/index.md
        - CanBoot <i>(optional)</i>: 3d-printing/klipper/canbus/mellow/fly-sht-v1/canboot.md
        - Klipper: 3d-printing/klipper/canbus/mellow/fly-sht-v1/klipper.md

  - Klipper Tutorials:
    - PA-Calibration with LA-Test: 3d-printing/klipper/pa-calibration-la-test/index.md
    - SSD1306 Display:
      - Overview: 3d-printing/klipper/ssd1306-display/index.md
      - RPi with Host-MCU: 3d-printing/klipper/ssd1306-display/rpi-host-mcu.md

  - Other Tutorials:
    - Snakeoil Certificates: other/snakeoil-certificates/index.md
