site_name: Klipper Misc Docs
theme:
  name: material
  language: en
  plugins:
    - navigation.indexes
    - search
    - content.code.copy
    - git-committers:
        repository: meteyou/docs
        branch: main
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - BigTreeTech U2C:
    - Overview: btt-u2c/index.md
    - Candlelight: btt-u2c/candlelight.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/meteyou
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@meteyou
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/meteyou

copyright: |
  &copy; 2023 <a href="https://github.com/meteyou"  target="_blank" rel="noopener">Stefan Dej (meteyou)</a>